//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18033
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XbyakSharp.Test {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpectedData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpectedData() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XbyakSharp.Test.ExpectedData", typeof(ExpectedData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   8B0C00
        ///8B4C0001
        ///8B8C00E8030000
        ///8B4C00FF
        ///8B8C0018FCFFFF
        ///8B0C00
        ///8B4C0001
        ///8B8C00E8030000
        ///8B4C00FF
        ///8B8C0018FCFFFF
        ///8B0C40
        ///8B4C4001
        ///8B8C40E8030000
        ///8B4C40FF
        ///8B8C4018FCFFFF
        ///8B0C80
        ///8B4C8001
        ///8B8C80E8030000
        ///8B4C80FF
        ///8B8C8018FCFFFF
        ///8B0CC0
        ///8B4CC001
        ///8B8CC0E8030000
        ///8B4CC0FF
        ///8B8CC018FCFFFF
        ///8B0C08
        ///8B4C0801
        ///8B8C08E8030000
        ///8B4C08FF
        ///8B8C0818FCFFFF
        ///8B0C08
        ///8B4C0801
        ///8B8C08E8030000
        ///8B4C08FF
        ///8B8C0818FCFFFF
        ///8B0C48
        ///8B4C4801
        ///8B8C48E8030000
        ///8B4C48FF
        ///8B8C4818FCFFFF
        ///8B0C88
        ///8B4C8801
        ///8B8C88E8030000 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mov_expected_32bit {
            get {
                return ResourceManager.GetString("mov_expected_32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   678B0C00
        ///678B4C0001
        ///678B8C00E8030000
        ///678B4C00FF
        ///678B8C0018FCFFFF
        ///678B0C00
        ///678B4C0001
        ///678B8C00E8030000
        ///678B4C00FF
        ///678B8C0018FCFFFF
        ///678B0C40
        ///678B4C4001
        ///678B8C40E8030000
        ///678B4C40FF
        ///678B8C4018FCFFFF
        ///678B0C80
        ///678B4C8001
        ///678B8C80E8030000
        ///678B4C80FF
        ///678B8C8018FCFFFF
        ///678B0CC0
        ///678B4CC001
        ///678B8CC0E8030000
        ///678B4CC0FF
        ///678B8CC018FCFFFF
        ///678B0C08
        ///678B4C0801
        ///678B8C08E8030000
        ///678B4C08FF
        ///678B8C0818FCFFFF
        ///678B0C08
        ///678B4C0801
        ///678B8C08E8030000
        ///678B4C08FF
        ///678B8C0818FCFFFF
        ///678B0C48
        ///678B4C4801
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mov_expected_64bit_1 {
            get {
                return ResourceManager.GetString("mov_expected_64bit_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8B0C00
        ///8B4C0001
        ///8B8C00E8030000
        ///8B4C00FF
        ///8B8C0018FCFFFF
        ///8B0C00
        ///8B4C0001
        ///8B8C00E8030000
        ///8B4C00FF
        ///8B8C0018FCFFFF
        ///8B0C40
        ///8B4C4001
        ///8B8C40E8030000
        ///8B4C40FF
        ///8B8C4018FCFFFF
        ///8B0C80
        ///8B4C8001
        ///8B8C80E8030000
        ///8B4C80FF
        ///8B8C8018FCFFFF
        ///8B0CC0
        ///8B4CC001
        ///8B8CC0E8030000
        ///8B4CC0FF
        ///8B8CC018FCFFFF
        ///8B0C08
        ///8B4C0801
        ///8B8C08E8030000
        ///8B4C08FF
        ///8B8C0818FCFFFF
        ///8B0C08
        ///8B4C0801
        ///8B8C08E8030000
        ///8B4C08FF
        ///8B8C0818FCFFFF
        ///8B0C48
        ///8B4C4801
        ///8B8C48E8030000
        ///8B4C48FF
        ///8B8C4818FCFFFF
        ///8B0C88
        ///8B4C8801
        ///8B8C88E8030000 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mov_expected_64bit_2 {
            get {
                return ResourceManager.GetString("mov_expected_64bit_2", resourceCulture);
            }
        }
    }
}
